### ISSUE TITLE
Invalidate the old payments

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/solidus_square#55]
At the moment, when a new payment is created the old payments are not invalidated.

This is because the payment is created in a pending state.

Probably instead of creating the payment [in this way](https://github.com/nebulab/solidus_square/blob/main/app/services/solidus_square/create_payment_service.rb#L31-L36) we should use the [PaymentCreate](https://github.com/solidusio/solidus/blob/f4b6de0872e1d2270d17671c7f1632d5bb33ee47/core/app/models/spree/payment_create.rb) service provided by solidus.

**Comment by garciajordy** [comment]
Instead of creating the payment on Square when creating the nonce we should instead store the nonce in the payment source and create the payment after the order is completed using the authorize method in the gateway.
